default: &default
  adapter: postgresql
  database: photo_development
  username: adelina
  password: parola
  host: localhost
  pool: 5
  timeout: 1000000

development:
  <<: *default
  database: photo_development


test:
  <<: *default
  database: photo_test

production:
  adapter: postgresql
  database: photo_development
  username: '<%= ENV["POSTGRES_USERNAME"] %>'
  password: '<%= ENV["POSTGRES_PASSWORD"] %>'
  host: localhost
  pool: 5
  timeout: 100000
