source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
#kaminari paginates
gem 'kaminari'
#pry is good at debugging
gem 'pry'
#json standard serializer
gem 'jsonapi-serializers'
#active_model_serializers will be deleted !
gem 'active_model_serializers'
#pg is used for a postgress database
gem 'pg',             '0.17.1'
#use carrierwave to store images
gem 'carrierwave',             '0.10.0'
gem 'carrierwave-base64'
gem 'mini_magick',             '3.8.0'
gem 'rails-angular-material'
gem 'fog',                     '1.23.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# contains data from the IANA Time Zone database packaged as Ruby modules for use with TZInfo
gem 'tzinfo-data'
# Rails integration for bower
gem 'bower-rails'
# use angular templates with asset pipeline
gem 'angular-rails-templates'
# injects MaterialDesign into  asset pipeline
gem 'bootstrap-material-design'

gem 'angularjs-file-upload-rails', '~> 1.1.6'

#for tests
gem 'rspec-rails'
gem 'factory_girl'
gem 'faker'
gem 'shoulda-matchers'
gem 'shoulda'

# user management
gem 'devise'

group :development, :test do
  #test bottlenecks
	#gem 'rack-mini-profiler'
	#test for eager loading
	gem 'bullet'
  gem 'webrat'
  gem "shoulda-kept-assign-to"
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end